### ISSUE TITLE
What does the "peers" requirement do?

### ISSUE THREAD

**Issue by jpgoldberg** [alecmuffett/draft-muffett-end-to-end-secure-messaging#3]
```
All participants
**MUST** be peers and
```

I do not know what that means. And I am wondering if it is necessary. (I don't know that it isn't necessary because I don't know what it means.)

**Comment by alecmuffett** [comment]
Looks like I need a rationale section.

**Comment by alecmuffett** [comment]
Rationale section added, does this help?
